let API_CREDENTIALS = {
	KEY: "API_KEY_GOES_HERE",
	SECRET: "API_SECRET_GOES_HERE"
};

let CRYPTOPIA_CREDENTIALS = {
	KEY: "API_KEY_GOES_HERE",
	SECRET: "API_SECRET_GOES_HERE"
};

export {API_CREDENTIALS, CRYPTOPIA_CREDENTIALS};